-- FamilyOS cron scheduling is configured in the Supabase Dashboard, not via
-- a SQL-managed pg_cron + Vault setup.
--
-- Why this migration is intentionally a no-op:
-- 1. Some Supabase projects do not expose the `vault` extension.
-- 2. The Dashboard Edge Function scheduler is the simpler and more portable
--    operational path for this project.
-- 3. FamilyOS uses one daily cron trigger in the Dashboard and lets the
--    `send-telegram-digests` Edge Function decide whether daily, weekly,
--    and/or monthly digests are due based on the Europe/London date.
--
-- Expected live configuration for `myworld`:
-- - one Supabase Dashboard cron job
-- - target: send-telegram-digests
-- - schedule: 0 6 * * *
--
-- See docs:
-- - docs/telegram-digests.md
-- - supabase/functions/send-telegram-digests/README.md
